### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by yuko29** [yuko29/meteorological_center#16]
### Todo 統整

- [x] 震度轉換成級數 @vivian96385 @Laxiflora 
- [x] 呈現水庫和電力資料更新時間 @HeywardLiu @410011max 
- [x] 警示功能 @HeywardLiu 
- [ ] 日期格式美化 (optional)
- [x] Reject insert incomplete data @vivian96385 @Laxiflora  

Logs
- [x] Crawling stdout log message @vivian96385 
- [x] Database stdout log message @Laxiflora 

DevOps
- [x] Automation: kubernetes dashboard setup @yuko29
- [ ] CI/CD (Unit Test) @yuko29 
- [x] Optimize manage scripts @yuko29 
- [x] Release versions @yuko29 
- [x] Environment variables @Laxiflora

**Comment by Laxiflora** [comment]
I will print error message in stdout (with print) **then raise exception (this is necessary for unit test to predict the output)** instead, please use `try ... except` to cover my API call

**Comment by Laxiflora** [comment]
@yuko29 hayward mentioned that caller process will dead if DB raise error during crawler API call in k8s.
Will this keep happen even though the caller provide `try ... except`?
Since raise exception is crucial for unit test to predict output, and is a good software design manner (compared to directly return None), I want to keep this feature.

**Comment by HeywardLiu** [comment]
@410011max 呈現水庫和電力資料更新時間 & 警示功能，我幫你做好了

**Comment by yuko29** [comment]
@Laxiflora DB API 設計 raise exception 是 ok 的，crwaling 因為 exception 程式中斷失敗也合理。
這個狀況應該是要 crawling 程式去處理這個 exception 沒錯，有 catch 到 exception 有處理好理應能正常結束。
